version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8090:8000"  # Cambiado de 8080 a 8090
    volumes:
      - .:/app
    depends_on:
      - mongo
    restart: on-failure
    environment:
      - MONGODB_URL=mongodb://admin:admin123@mongo:27017/cafeteria_db?authSource=admin
      - FORCE_INIT=true  # Nueva variable para forzar inicialización

  mongo:
    image: mongo:7.0
    ports:
      - "27018:27017"  # MANTENER como estaba (27018)
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=cafeteria_db
    restart: unless-stopped
    command: ["mongod", "--auth"]  # Asegurar autenticación

  mongo-express:
    image: mongo-express:1.0.0
    ports:
      - "8082:8081"  # MANTENER como estaba (8082)
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin123
      - ME_CONFIG_MONGODB_URL=mongodb://admin:admin123@mongo:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local